// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyClk3sj5d5b0vE3wEkauH0himlxDTdKa5s',
//     appId: '1:394313715853:web:a7b4b2a2982ff938f052c4',
//     messagingSenderId: '394313715853',
//     projectId: 'carrentalflutter-287cb',
//     authDomain: 'carrentalflutter-287cb.firebaseapp.com',
//     storageBucket: 'carrentalflutter-287cb.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAFuQF3A_08_GnpxlhI5M3K0850b9HLQtU',
//     appId: '1:394313715853:android:63c908bbab0fccf5f052c4',
//     messagingSenderId: '394313715853',
//     projectId: 'carrentalflutter-287cb',
//     storageBucket: 'carrentalflutter-287cb.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAuRtbQ2uVRlB38qVY53VAhrGHGmEHkL54',
//     appId: '1:394313715853:ios:86e0487bfe0e1faaf052c4',
//     messagingSenderId: '394313715853',
//     projectId: 'carrentalflutter-287cb',
//     storageBucket: 'carrentalflutter-287cb.firebasestorage.app',
//     iosBundleId: 'com.example.rentcar',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAuRtbQ2uVRlB38qVY53VAhrGHGmEHkL54',
//     appId: '1:394313715853:ios:86e0487bfe0e1faaf052c4',
//     messagingSenderId: '394313715853',
//     projectId: 'carrentalflutter-287cb',
//     storageBucket: 'carrentalflutter-287cb.firebasestorage.app',
//     iosBundleId: 'com.example.rentcar',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyClk3sj5d5b0vE3wEkauH0himlxDTdKa5s',
//     appId: '1:394313715853:web:96aeb1eff806acf3f052c4',
//     messagingSenderId: '394313715853',
//     projectId: 'carrentalflutter-287cb',
//     authDomain: 'carrentalflutter-287cb.firebaseapp.com',
//     storageBucket: 'carrentalflutter-287cb.firebasestorage.app',
//   );
// }
